#!/bin/bash

ZIPNAME=${CIRCLE_BRANCH}"-"${CIRCLE_BUILD_NUM}"-"${CIRCLE_SHA1}".zip"

# push apps to S3
S3INFO=`aws deploy push \
          --application-name ${CODE_DEPLOY_APPLICATION_NAME} \
          --s3-location s3://${CODE_DEPLOY_S3_BUCKET_NAME}/${ZIPNAME} \
          --source ${APP_DIR} | grep eTag`
ETAG=`echo "${S3INFO}" | sed -e 's/^.*eTag=\([^ ]*\) .*$/\1/g'`

echo ${ETAG};

# create codedeploy deployment
DEPLOY=`aws deploy create-deployment \
   --application-name ${CODE_DEPLOY_APPLICATION_NAME} \
   --s3-location bucket=${CODE_DEPLOY_S3_BUCKET_NAME},key=${ZIPNAME},bundleType=zip,eTag=${ETAG} \
   --deployment-group-name ${CODE_DEPLOY_GROUP_NAME}`

echo ${DEPLOY}

DEPLOYMENT_ID=`echo ${DEPLOY} | jq .deploymentId | sed -e 's/"//g'`

echo ${DEPLOYMENT_ID}

# wait for codedeploy finishes deployment
aws deploy wait deployment-successful --deployment-id ${DEPLOYMENT_ID}